/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Week08Midterm;

/**
 *
 * @author ali.nizam
 */
public class Question2 extends javax.swing.JFrame {
    class Employee {     String name;     Department department;

        public Employee(String name, Department department) {
            this.name = name;
            this.department = department;
        }
    
    }
    
    public class Department {     String name; 
        public Department(String name) {         this.name = name;     }
    } 

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Question2.class.getName());

    /**
     * Creates new form Question2
     */
    Employee[] employees=new Employee[3];
    public Question2() {
        initComponents();
        cbEmployee.removeAllItems();
        cbDepartment.removeAllItems();
        employees[0]=new Employee("Ahmet",new Department("IT"));
        employees[1]=new Employee("Mehmet",new Department("IT"));
        employees[2]=new Employee("Ayşe",new Department("HR"));
        cbDepartment.addItem("IT");
        cbDepartment.addItem("HR");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbDepartment = new javax.swing.JComboBox<>();
        cbEmployee = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDepartment.setSelectedIndex(-1);
        cbDepartment.addItemListener(this::cbDepartmentİtemStateChanged);

        cbEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbDepartment, 0, 210, Short.MAX_VALUE)
                    .addComponent(cbEmployee, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(cbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbDepartmentİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDepartmentİtemStateChanged
        // TODO add your handling code here:
        String selectedDepartment=(String)cbDepartment.getSelectedItem();
        cbEmployee.removeAllItems();
        for (Employee employee : employees) {
            if (employee.department.name.equals(selectedDepartment)){
                cbEmployee.addItem(employee.name);
            }
        }
    }//GEN-LAST:event_cbDepartmentİtemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Question2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDepartment;
    private javax.swing.JComboBox<String> cbEmployee;
    // End of variables declaration//GEN-END:variables
}
